---
title: "StupidBackoff"
author: "Jeff Sternin"
date: "May 3, 2018"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(quanteda)
library(dplyr)
library(data.table)
```

```{r load_dt1, echo = TRUE, include = TRUE}
nf1 <- nfeat(dfms1) # number of features
fre1 <- textstat_frequency(dfms1,nf1) # stats
tot1 <- sum(fre1$frequency) # total number of counts
dt1<- data.table(name=fre1$feature,p=fre1$frequency/tot1,count=fre1$frequency)
setkey(dt1,name)
rm(fre1)
saveRDS(dt1,file="dt1.rds")
```

```{r func_getdt, echo = TRUE, include = TRUE}
builddt<- function(dfms,dtPr) {## Cr - current, Pr - previous
  nf <- nfeat(dfms) # number of features
  fre <- textstat_frequency(dfms,nf) # stats
  #tot2 <- sum(fre2$frequency) # total number of counts
  dtCr<- data.table(name=fre$feature,p=fre$frequency,count=fre$frequency)
  setkey(dtCr,name)
  firstpart <- substring(dtCr$name,1,regexpr("\ [^\ ]*$", dtCr$name)-1) ## part before last space
  dtCrsum <- dtCr %>% group_by( substring(dtCr$name,1,regexpr("\ [^\ ]*$", dtCr$name)-1))
  names(dtCrsum) <- c("name","p","count" ,"fp")
  dtCrx <- dtCrsum %>% group_by(name=fp) %>% summarise(sm = sum(p)) %>% as.data.table
  setkey(dtCrx,name)
  dtCr$p <- dtCr$p / dtCrx[firstpart]$sm
  afterspace<- substring(dtCr$name,nchar(strsplit(dtCr$name," ")[[1]][1])+2)  ## first part of the key
  dtCrp <- dtCr$p
  dtPrap <- dtPr[afterspace]$p
  dtCr$p <- ifelse(is.na(dtPrap) | dtCrp > 0.4*dtPrap,dtCrp, dtPrap)
  rm(fre)
  rm(dtCrsum)
  rm(dtCrp)
  rm(dtPrap)
  rm(firstpart)
  rm(afterspace)
  dtCr
  ##saveRDS(dtCr,file="dt2.rds")
}
```

```{r load_dt2, echo = TRUE, include = TRUE}
dt2 <- builddt(dfms2,dt1)
saveRDS(dt2,file="dt2.rds")
```

```{r load_dt3, echo = TRUE, include = TRUE}
dt3 <- builddt(dfms3,dt2)
saveRDS(dt3,file="dt3.rds")
```

```{r load_dt4, echo = TRUE, include = TRUE}
dt4 <- builddt(dfms4,dt3)
saveRDS(dt4,file="dt4.rds")
```


```{r load_dt5, echo = TRUE, include = TRUE}
dt5 <- builddt(dfms5,dt4)
saveRDS(dt5,file="dt5.rds")
```


```{r load_dt6, echo = TRUE, include = TRUE}
dt6 <- builddt(dfms6,dt5)
saveRDS(dt6,file="dt6.rds")
```

```{r stpd_predict_word, echo = TRUE, include = TRUE}
dt6 <- builddt(dfms6,dt5)
saveRDS(dt6,file="dt6.rds")
```




```{r select_from_dt, echo = TRUE, include = TRUE}
select_from_dt<-function(sx,i) {
  
  #print(sprintf("select_from_dfm i:%d, dfms%d, sx:%s",i,i,sx))
  switch(as.character(i),
      "6" = dtx <- dt6[name %>% like(sx)],     
      "5" = dtx <- dt5[name %>% like(sx)],
      "4" = dtx <- dt4[name %>% like(sx)],
      "3" = dtx <- dt3[name %>% like(sx)],
      "2" = dtx <- dt2[name %>% like(sx)],
      "1" = dtx <- dt1[name %>% like(sx)],
      print(sprintf("i not found: %d %s",i,as.character(i)))
      
    )
}
```


```{r empty_reply, echo = TRUE, include = TRUE}
##
## small helpers
##
empty_reply<-function(stupid) {
  if (stupid)
      return(data.table(word=as.character(),prob=as.double()))
  return(data.table(word=as.character(),count=as.integer()))
}
dosort<-function(dtx,stupid){
  if (stupid)
    dtx <- dtx[order(-p)]
  else
    dtx <- dtx[order(-count)]
  dtx
}
getcols<-function(dtx1,stupid) {
  if (stupid) {
    dtx1 <- select(dtx1,-count)
    names(dtx1)<-c("word","prob")
  }
  else {
    dtx1 <- select(dtx1,-p)
    names(dtx1)<-c("word","count")
  }
  return(dtx1)
}

```


## 1. Stupid predict word

```{r stpd_predict_word, echo = TRUE, include = TRUE}
stupid_predict_word<- function(str,stupid=TRUE) {
  if (nchar(str)==0) 
    return( empty_reply(stupid))
  savestr <- str
  for(i in seq(6,1,by=-1)) {
    str <- savestr
    str <- prep(str,TRUE)[[1]]
    if(length(str) <= (i-2))
      next
    sx <- strbo(str,i)
    if (i > 1) 
      sx <- paste0(sx," ")
    #print(sx)
    dtx <- select_from_dt(sx,i)
    nrow <-nrow(dtx)
    #print(sprintf("i:%d,nrow:%d sx:%s",i,nrow,sx))
    if (nrow==0)
      next
    dtx<-dosort(dtx,stupid)
    #print(dtx)
    nwords <- min(5,nrow)
    dtx <- dtx[1:nwords]
    dtx1 <- dtx
    dtx1$name <- substring(dtx$name,regexpr("\ [^\ ]*$", dtx$name)+1)
    #print(dtx1)
    return(getcols(dtx1,stupid))
  } 
  return( empty_reply(stupid))
}
```


```{r test_stupid_predict_word, echo = TRUE, include = TRUE}
#s <- "this is my presentation. Let me know what you"
#s <- "I like how the same people are in almost all of Adam Sandler's"
#s <- "to be or not to be that is the"
#s <- "help me if you can i'm"
s <- "how are you"
#s <-"I chose the road Less"
#s <-""
stupid = FALSE
dtx <- stupid_predict_word(s,stupid)
print(dtx)
#print(nrow(reswp))
for(k in 1: nrow(dtx)) {
  if (stupid)
    print(sprintf("%d : count:%6.5f word:%s",k,dtx[k]$p,dtx[k]$word))
  else
    print(sprintf("%d : count:%d word:%s",k,dtx[k]$count,dtx[k]$word))
    
}
```

## 3. STUPID PREDICT CHAR-BY-CHAR

```{r stupid_predict_char_by_char, echo = TRUE, include = TRUE}
stupid_char_by_char<-function(str,chars_str,stupid=TRUE) { ## bchars if this is first
  if (nchar(str)==0)
    return( empty_reply(stupid))
  if (nchar(chars_str)==0)
    return (stupid_predict_word(str,stupid))
  str1 <- sprintf("%s %s",str,chars_str) 
  savestr <- str1
  for(i in seq(6,1,by=-1)) {
    str <- savestr
    str <- prep(str,TRUE)[[1]]
    if(length(str) <= (i-2))
      next
    sx <- strbo(str,i+1)
    dtx <- select_from_dt(sx,i)
    nrow <-nrow(dtx)
    #print(sprintf("i:%d,nrow:%d sx:%s",i,nrow,sx))
    if (nrow==0)
      next
    #print(dtx)
    dtx<-dosort(dtx,stupid)
    #print(dtx)
    nwords <- min(5,nrow)
    dtx <- dtx[1:nwords]
    dtx1 <- dtx
    dtx1$name <- substring(dtx$name,regexpr("\ [^\ ]*$", dtx$name)+1)
    #print(dtx1)
    return(getcols(dtx1,stupid))
  }
  return( empty_reply(stupid))
}

```

```{r test_stupid_predict_charbychar, echo = TRUE, include = TRUE}
#s <- "When you were in Holland you were like 1 inch away from me but you hadn't time to take a"
#s <- "I like how the same people are in almost all of Adam Sandler's"
s <- "help me if you can i'm"
#---s <- "Guy at my table's wife got up to go to the bathroom and I asked about dessert and he started telling me about his"
stupid=TRUE
dtx <- stupid_char_by_char(s,"f",stupid)
print(dtx)
for(k in 1: nrow(dtx)) {
  if (stupid)
    print(sprintf("%d : count:%6.5f word:%s",k,dtx[k]$p,dtx[k]$word))
  else
    print(sprintf("%d : count:%6d word:%s",k,dtx[k]$count,dtx[k]$word))
    
}
```

## 2. FIND THE BEST HINT (QUIZ)

```{r stupid_predict_find_answer, echo = TRUE, include = TRUE}
## try to find if words exists in dmf 
## if yes find the most probable
stupid_find_answer<-function(sx,answer,dtf,i,stupid=TRUE) {
  
  nrow <- nrow(dtf)
  #print(sprintf("1. st_find answer dtf nrow:%d",nrow))
  if (nrow == 0 )
    return( empty_reply(stupid))
  found<-FALSE
  for(j in 1:length(answer)) { ## scan all words in test and find one with top position
    sans <- sprintf("%s %s$",sx,answer[j])
    dtt <- dtf[name %>% like(sans)] 
    #print(sprintf("2. st_find answer dtt nrow:%d  answer[j]$:%s",nrow(dtt),sans))
    if (nrow(dtt) == 0)
      next
    if(!found)
      dtx <- dtt
    else
      dtx<- rbind(dtx,dtt[1,])
    
    found<-TRUE  
  }   
  if (found) 
    dtx<-dosort(dtx,stupid)
    #print(dtx)
  else 
    return( empty_reply(stupid))
  dtx
}
 
```

```{r stupid_predict_quiz, echo = TRUE, include = TRUE}
stupid_predict_quiz<-function(str,answer_str,stupid=TRUE) {
  if (nchar(str)==0 || nchar(answer_str) == 0)
    return( empty_reply(stupid))
  ans <- tokens(answer_str, ngrams = 1) %>%
       tokens_tolower() %>%
       tokens(remove_punct=TRUE)
  answer<- ans[[1]]
  #print(sprintf("phrase:%s",str))
  #print(sprintf("possible answers:%s",answer_str))
  savestr <- str
  # check aginst dfm with stop words present
  
  for(i in seq(6,1,by=-1)) {
    str <- savestr
    str <- prep(str,TRUE)[[1]] ## str array of words from string
    #print(sprintf("in predict quiz: savestr: %s,str:%s",savestr,str))
    if(length(str) <= (i-2))
      next
    sx <- strbo(str,i)
    #print(sx)
    dtf <- select_from_dt(sx,i)
    nrow <-nrow(dtf)
    #print(sprintf("i:%d,dtf nrow:%d sx:%s",i,nrow,sx))
    if (nrow==0)
      next
    dtx <- stupid_find_answer(sx,answer,dtf,i,stupid)
    #print(sprintf("i:%d,dtx nrow:%d sx:%s",i,nrow,sx))
    if(nrow(dtx)==0)
      next
    #print(sprintf("result found in dt%d nrows:%d, topprob:%6.5f top word:%s",
    #       i, nrow(dtx),dtx[1]$p,dtx[1]$name))
    dtx1 <- dtx
    dtx1$name <- substring(dtx$name,regexpr("\ [^\ ]*$", dtx$name)+1)
    return(getcols(dtx1,stupid))
    
  }
  return( empty_reply(stupid))
  
}

```




```{r do_stupid_quiz, echo = TRUE, include = TRUE}
do_stupid_quiz<-function(quiz_name,q,stupid=TRUE) {
  print(quiz_name)
  for(i in 1:length(q)) {
    #print(sprintf("**question: %d",i))
    s <- unlist(q[[i]][1])
    answer_str <- unlist(q[[i]][2])
    print(sprintf("question:%d :%s",i,s))
    print(sprintf("answer(s) :%s",answer_str))
    #print(sprintf("++searching for answer question...: %d",i))
    dtx<-stupid_predict_quiz(s,answer_str,stupid)
    print(dtx)
    for(k in 1: nrow(dtx)) {
      if (stupid)
        print(sprintf("%d : count:%6.5f word:%s",k,dtx[k]$p,dtx[k]$word))
      else
        print(sprintf("%d : count:%6d word:%s",k,dtx[k]$count,dtx[k]$word))
    
}
  }  
}
```

```{r predict_stupid_quiz2, echo = TRUE, include = TRUE}
##QUIZ2

q1 <- list(s ="The guy in front of me just bought a pound of bacon, a bouquet, and a case of",
    ans= "pretzels soda cheese beer")
 
q2 <- list("You're the reason why I smile everyday. Can you follow me please? It would mean the",
    c("universe world best most"))
q3 <- list("Hey sunshine, can you follow me and make me the",
    c("bluest happiest smelliest saddest"))
q4 <- list("Very early observations on the Bills game: Offense still struggling but the",
    c("players crowd defense referees"))
q5 <- list("Go on a romantic date at the",
    c("mall beach grocery movies"))
q6 <- list("Well I'm pretty sure my granny has some old bagpipes in her garage I'll dust them off and be on my",
    c("motorcycle phone horse way"))
q7 <- list("Ohhhhh #PointBreak is on tomorrow. Love that film and haven't seen it in quite some",
    c("years thing time weeks"))
q8 <- list("After the ice bucket challenge Louis will push his long wet hair out of his eyes with his little",
    c("eyes toes ears fingers"))
q9 <- list("Be grateful for the good times and keep the faith during the",
    c("hard worse sad bad"))
q10 <- list("If this isn't the cutest thing you've ever seen, then you must be",
    c("insensitive callous insane asleep"))
stupid=FALSE
q <- list(q1,q2,q3,q4,q5,q6,q7,q8,q9,q10)
do_stupid_quiz("QUIZ 2",q,stupid)
```

```{r stupid_predict_quiz3, echo = TRUE, include = TRUE}
##QUIZ3

q1 <- list(s ="When you breathe, I want to be the air for you. I'll be there for you, I'd live and I'd",
    ans=c("sleep eat die give"))

q2 <- list(
  "Guy at my table's wife got up to go to the bathroom and I asked about dessert and he started telling me about his",
  c("horticultural financial spiritual marital"))
q3 <- list("I'd give anything to see arctic monkeys this",
    c("decade weekend month morning"))
q4 <- list("Talking to your mom has the same effect as a hug and helps reduce your",
    c("stress sleepiness happiness hunger"))
q5 <- list("When you were in Holland you were like 1 inch away from me but you hadn't time to take a",
    c("walk minute look picture"))
q6 <- list("I'd just like all of these questions answered, a presentation of evidence, and a jury to settle the",
    c("case incident matter account"))
q7 <- list("I can't deal with unsymetrical things. I can't even hold an uneven number of bags of groceries in each",
    c("toe arm hand finger"))
q8 <- list("Every inch of you is perfect from the bottom to the",
    c("top center middle side"))
q9 <- list("I'm thankful my childhood was filled with imagination and bruises from playing",
    c("outside weekly inside daily"))
q10 <- list("I like how the same people are in almost all of Adam Sandler's",
    c("stories pictures novels movies"))
stupid=FALSE
q <- list(q1,q2,q3,q4,q5,q6,q7,q8,q9,q10)
do_stupid_quiz("QUIZ 3",q,stupid)
```


```{r load_dt2TEST, echo = TRUE, include = TRUE}
nf2 <- nfeat(dfms2) # number of features
fre2 <- textstat_frequency(dfms2,nf2) # stats
#tot2 <- sum(fre2$frequency) # total number of counts
dt2<- data.table(name=fre2$feature,p=fre2$frequency)
setkey(dt2,name)
firstpart <- substring(dt2$name,1,regexpr("\ [^\ ]*$", dt2$name)-1) ## part before last space
dt2sum <- dt2 %>% group_by( substring(dt2$name,1,regexpr("\ [^\ ]*$", dt2$name)-1))
names(dt2sum) <- c("name","p","fp")
dt2x <- dt2sum %>% group_by(name=fp) %>% summarise(sm = sum(p)) %>% as.data.table
setkey(dt2x,name)
dt2$p <- dt2$p / dt2x[firstpart]$sm
afterspace<- substring(dt2$name,nchar(strsplit(dt2$name," ")[[1]][1])+2)  ## first part of the key
dt2p <- dt2$p
dt1ap <- dt1[afterspace]$p
dt2$p <- ifelse(is.na(dt1ap) | dt2p > 0.4*dt1ap,dt2p, dt1ap)
rm(fre2)
rm(dt2p)
rm(dt2x)
rm(dt1ap)
saveRDS(dt2,file="dt2.rds")
```























